// Mock Data para desarrollo y demostración
// 6 subvenciones de ejemplo que muestren todas las funcionalidades

import type { Subvencion } from '@/types';

export const MOCK_SUBVENCIONES: Subvencion[] = [
  {
    id: '1',
    bdns: '123456',
    titulo: 'Programa Kit Digital PYME 2025 - Transformación Digital',
    descripcion: 'Subvenciones para la digitalización de pequeñas y medianas empresas mediante la implementación de soluciones tecnológicas avanzadas. Incluye desarrollo web, e-commerce, CRM, ERP y ciberseguridad.',
    organismo: 'Ministerio de Asuntos Económicos y Transformación Digital',
    cuantia: 125000,
    fechaInicio: '2025-01-15',
    fechaFin: '2025-03-31',
    beneficiarios: ['PYMES', 'Autónomos', 'Microempresas'],
    categorias: ['Digitalización', 'Innovación', 'Empresa'],
    sectores: ['Tecnología e Informática', 'Servicios Profesionales'],
    comunidadAutonoma: 'Nacional',
    url: 'https://www.acelerapyme.gob.es/kit-digital',
    boletin: 'BOE',
    estado: 'abierto',
    tiposEntidad: ['pyme', 'autonomo'],
    requisitoAmbiental: false,
    requisitoIgualdad: true,
    esDigital: true,
    esCircular: false,
    paraJovenes: false,
    zonaRural: false,
    tipoFinanciacion: 'subvencion',
    intensidadAyuda: 80,
    garantiasRequeridas: false,
    anticipoDisponible: true,
    compatibleOtrasAyudas: true,
    complejidadAdministrativa: 'baja',
    probabilidadConcesion: 75,
    competitividad: 'media',
    requiereSeguimiento: true,
    requiereAuditoria: false,
    pagosIntermedios: true,
    etiquetas: [
      { id: '1', nombre: 'Digital', color: '#3B82F6', categoria: 'requisito' },
      { id: '2', nombre: 'PYME', color: '#10B981', categoria: 'beneficiario' },
      { id: '3', nombre: 'Urgente', color: '#F59E0B', categoria: 'urgencia' }
    ],
    diasRestantes: 45,
    innovacionSocial: false
  },
  {
    id: '2', 
    bdns: '789012',
    titulo: 'Ayudas para Proyectos de I+D+i en Biotecnología Médica',
    descripcion: 'Financiación para proyectos de investigación, desarrollo e innovación en el sector de la biotecnología aplicada a la salud. Dirigido a centros de investigación y empresas del sector farmacéutico.',
    organismo: 'Ministerio de Ciencia e Innovación - CDTI',
    cuantia: 2500000,
    fechaInicio: '2024-11-15',
    fechaFin: '2025-01-30',
    beneficiarios: ['Centros de investigación', 'Universidades', 'Empresas biotecnológicas'],
    categorias: ['I+D+i', 'Salud', 'Biotecnología'],
    sectores: ['Salud y Biotecnología', 'Educación y Formación'],
    comunidadAutonoma: 'Nacional',
    url: 'https://www.cdti.es',
    boletin: 'BOE',
    estado: 'cerrado',
    tiposEntidad: ['universidad', 'centro_investigacion', 'gran_empresa'],
    requisitoAmbiental: true,
    requisitoIgualdad: true,
    esDigital: false,
    esCircular: false,
    paraJovenes: true,
    zonaRural: false,
    tipoFinanciacion: 'prestamo',
    intensidadAyuda: 75,
    garantiasRequeridas: true,
    anticipoDisponible: false,
    compatibleOtrasAyudas: false,
    complejidadAdministrativa: 'alta',
    probabilidadConcesion: 45,
    competitividad: 'alta',
    requiereSeguimiento: true,
    requiereAuditoria: true,
    pagosIntermedios: false,
    etiquetas: [
      { id: '4', nombre: 'I+D+i', color: '#8B5CF6', categoria: 'sector' },
      { id: '5', nombre: 'Biotecnología', color: '#EC4899', categoria: 'sector' },
      { id: '6', nombre: 'Cerrado', color: '#EF4444', categoria: 'urgencia' }
    ],
    diasRestantes: -15,
    innovacionSocial: true
  },
  {
    id: '3',
    bdns: '345678',
    titulo: 'Subvenciones para Emprendimiento Femenino en Zonas Rurales',
    descripcion: 'Programa de apoyo al emprendimiento de mujeres en municipios de menos de 10.000 habitantes. Incluye formación, mentoring y financiación para startups lideradas por mujeres en sectores tradicionales y digitales.',
    organismo: 'Instituto de la Mujer y para la Igualdad de Oportunidades',
    cuantia: 45000,
    fechaInicio: '2025-03-01',
    fechaFin: '2025-06-15',
    beneficiarios: ['Mujeres emprendedoras', 'Startups rurales', 'Cooperativas'],
    categorias: ['Empleo', 'Igualdad', 'Emprendimiento'],
    sectores: ['Agricultura y Alimentación', 'Servicios Profesionales', 'Turismo y Hostelería'],
    comunidadAutonoma: 'Castilla-La Mancha',
    url: 'https://www.inmujeres.gob.es',
    boletin: 'DOCM',
    estado: 'proximo',
    tiposEntidad: ['startup', 'cooperativa', 'persona_fisica'],
    requisitoAmbiental: false,
    requisitoIgualdad: true,
    esDigital: false,
    esCircular: false,
    paraJovenes: true,
    zonaRural: true,
    tipoFinanciacion: 'subvencion',
    intensidadAyuda: 85,
    garantiasRequeridas: false,
    anticipoDisponible: true,
    compatibleOtrasAyudas: true,
    complejidadAdministrativa: 'baja',
    probabilidadConcesion: 65,
    competitividad: 'baja',
    requiereSeguimiento: false,
    requiereAuditoria: false,
    pagosIntermedios: true,
    etiquetas: [
      { id: '7', nombre: 'Igualdad', color: '#EC4899', categoria: 'requisito' },
      { id: '8', nombre: 'Rural', color: '#84CC16', categoria: 'requisito' },
      { id: '9', nombre: 'Próximo', color: '#06B6D4', categoria: 'urgencia' }
    ],
    diasRestantes: 120,
    innovacionSocial: true
  },
  {
    id: '4',
    bdns: '567890',
    titulo: 'Incentivos para la Industria 4.0 y Fabricación Avanzada',
    descripcion: 'Ayudas para la modernización de procesos industriales mediante tecnologías 4.0: IoT, IA, robótica colaborativa, gemelos digitales y análisis de datos. Enfocado en la mejora de la competitividad y sostenibilidad.',
    organismo: 'Ministerio de Industria, Comercio y Turismo',
    cuantia: 750000,
    fechaInicio: '2025-01-20',
    fechaFin: '2025-04-30',
    beneficiarios: ['Empresas industriales', 'Fabricantes', 'Proveedores tecnológicos'],
    categorias: ['Industria 4.0', 'Innovación', 'Digitalización'],
    sectores: ['Industria y Manufactura', 'Tecnología e Informática'],
    comunidadAutonoma: 'País Vasco',
    url: 'https://www.mincotur.gob.es',
    boletin: 'BOPV',
    estado: 'abierto',
    tiposEntidad: ['pyme', 'gran_empresa'],
    requisitoAmbiental: true,
    requisitoIgualdad: false,
    esDigital: true,
    esCircular: true,
    paraJovenes: false,
    zonaRural: false,
    tipoFinanciacion: 'mixto',
    intensidadAyuda: 70,
    garantiasRequeridas: true,
    anticipoDisponible: false,
    compatibleOtrasAyudas: false,
    complejidadAdministrativa: 'alta',
    probabilidadConcesion: 55,
    competitividad: 'alta',
    requiereSeguimiento: true,
    requiereAuditoria: true,
    pagosIntermedios: true,
    etiquetas: [
      { id: '10', nombre: 'Industria 4.0', color: '#7C3AED', categoria: 'sector' },
      { id: '11', nombre: 'Sostenible', color: '#10B981', categoria: 'requisito' },
      { id: '12', nombre: 'Alta Competencia', color: '#F97316', categoria: 'urgencia' }
    ],
    diasRestantes: 85,
    innovacionSocial: false
  },
  {
    id: '5',
    bdns: '901234',
    titulo: 'Programa de Transición Energética para Comercio Local',
    descripcion: 'Subvenciones para la instalación de sistemas de energías renovables en comercios locales: paneles solares, sistemas de almacenamiento, puntos de recarga eléctrica y mejoras en eficiencia energética.',
    organismo: 'Instituto para la Diversificación y Ahorro de la Energía (IDAE)',
    cuantia: 35000,
    fechaInicio: '2025-02-01',
    fechaFin: '2025-05-15',
    beneficiarios: ['Comercios locales', 'Autónomos del comercio', 'Pequeñas empresas'],
    categorias: ['Energía', 'Sostenibilidad', 'Comercio'],
    sectores: ['Comercio y Distribución', 'Energía y Utilities'],
    comunidadAutonoma: 'Comunidad Valenciana',
    url: 'https://www.idae.es',
    boletin: 'DOGV',
    estado: 'abierto',
    tiposEntidad: ['autonomo', 'pyme'],
    requisitoAmbiental: true,
    requisitoIgualdad: false,
    esDigital: false,
    esCircular: true,
    paraJovenes: false,
    zonaRural: false,
    tipoFinanciacion: 'subvencion',
    intensidadAyuda: 90,
    garantiasRequeridas: false,
    anticipoDisponible: true,
    compatibleOtrasAyudas: true,
    complejidadAdministrativa: 'media',
    probabilidadConcesion: 80,
    competitividad: 'baja',
    requiereSeguimiento: true,
    requiereAuditoria: false,
    pagosIntermedios: false,
    etiquetas: [
      { id: '13', nombre: 'Energía Verde', color: '#10B981', categoria: 'sector' },
      { id: '14', nombre: 'Comercio Local', color: '#F59E0B', categoria: 'beneficiario' },
      { id: '15', nombre: 'Alta Probabilidad', color: '#22C55E', categoria: 'urgencia' }
    ],
    diasRestantes: 75,
    innovacionSocial: false
  },
  {
    id: '6',
    bdns: '456789',
    titulo: 'Ayudas para Cooperativas de Economía Social y Solidaria',
    descripcion: 'Financiación para cooperativas y empresas de economía social que desarrollen proyectos de impacto social positivo, inserción laboral de colectivos vulnerables y modelos de negocio sostenibles y colaborativos.',
    organismo: 'Ministerio de Trabajo y Economía Social',
    cuantia: 85000,
    fechaInicio: '2025-01-10',
    fechaFin: '2025-03-20',
    beneficiarios: ['Cooperativas', 'Empresas de inserción', 'ONGs'],
    categorias: ['Economía Social', 'Empleo', 'Innovación Social'],
    sectores: ['Economía Social', 'Servicios Profesionales'],
    comunidadAutonoma: 'Andalucía',
    url: 'https://www.mites.gob.es',
    boletin: 'BOJA',
    estado: 'abierto',
    tiposEntidad: ['cooperativa', 'ong'],
    requisitoAmbiental: false,
    requisitoIgualdad: true,
    esDigital: false,
    esCircular: false,
    paraJovenes: true,
    zonaRural: true,
    tipoFinanciacion: 'avales',
    intensidadAyuda: 95,
    garantiasRequeridas: false,
    anticipoDisponible: false,
    compatibleOtrasAyudas: true,
    complejidadAdministrativa: 'media',
    probabilidadConcesion: 70,
    competitividad: 'media',
    requiereSeguimiento: false,
    requiereAuditoria: false,
    pagosIntermedios: true,
    etiquetas: [
      { id: '16', nombre: 'Economía Social', color: '#EC4899', categoria: 'sector' },
      { id: '17', nombre: 'Impacto Social', color: '#8B5CF6', categoria: 'requisito' },
      { id: '18', nombre: 'Cooperativas', color: '#06B6D4', categoria: 'beneficiario' }
    ],
    diasRestantes: 52,
    innovacionSocial: true
  }
];

export default MOCK_SUBVENCIONES;
